language: java
jdk:
  - oraclejdk8
  - openjdk8
env:
  - VRA_URL=https://api.mgmt.cloud.vmware.com
  - secure: "vNOZgXMzYaySpjOJT6BTnLDs5IUWmYDzl9BTk3Yvq2gy4QBzwLQStoAe2L2e1g4gDokelEnVL2kZQR1ubSQe5dx7Ig5wfrYbe0QVuT5moLZBm3pPTNC4f+GUZq7FUrZW/fl7rxIILObKm513NiNCZXmrFeMhjkREuvb1y5WQJfRd+zF1tYw8IpvvoKFAucC418jcQI8L6BEfQwzZwjtuA5HTlo+MMema00dQSerbJMtOYXYV3lPyX2QKWo2DaZTCEnSV1WpXKWpw6fAyPSYQuMDYsQUo0fkU9keCG3t5xa/nRuHjR+ZaOZQrAfUXr3buESEFRB2e8BuQLXKSVhu2vYb1M+yvZYT0gGr1AS0Il949gP7R1ccf7lLZZiv1adIMrfqqQL4uRmLl0nEXRXm4nP1QGNPbFRB+hzAaQgerzYCSlyHE2+fHDGhl8HR5Px4GzZEutcjBpDtx4HArIoqtp6xpWPVzYQ4I4Y/V1mJXyFf+PmMYecmx1hGPUhyWa3PRY5jNqr50ToI3MDb2CghxjefahTHcQUP0dMapxzeW2jC+YYekkHuZ0lAHDQes3XG02AuwZgo09nFZSBITUXYv0l3V3gt2SGZjwUIDkQAuRYalv8514tdzAOR6U4VpD984hC/9/eMicvL3WzLonz8ydNH91+hhIbWN0kTVAMwtENo="
